language: node_js
node_js: "10.15.0"
os: linux
before_install:
  - 'export PATH=./node_modules/.bin:$PATH'
  - 'npm install -g typescript'
  - 'npm install -g vsce'
install:
  - 'npm install'
script:
  - 'vsce package'
cache:
  directories:
    - "node_modules"
