version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^dependabot.*$/

jobs:
  build:
    working_directory: ~/vscode-camel-extension-pack
    docker:
      - image: cimg/node:14.18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-typescript
          command: npm install --prefix=$HOME/.local -g typescript
      - run:
          name: install-vsce
          command: npm install --prefix=$HOME/.local -g vsce
      - run:
          name: npm-install
          command: npm install
      - run:
          name: vsce-package
          command: vsce package
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
