name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CODE_VERSION: max
      TEST_RESOURCES: test-resources
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup dependencies
        run: |
          npm install -g typescript @vscode/vsce
          vsce --version

      - name: npm-ci
        run: npm ci

      - name: npm-compile
        run: npm run compile

      - name: UI test
        run: xvfb-run --auto-servernum npm run ui-test

      - name: Store UI test log
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: uitest-logs
          path: test-resources/settings/logs/*

      - name: Store UI Test screenshots
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: uitest-screenshots
          path: test-resources/screenshots/*.png
