name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CODE_VERSION: max
      TEST_RESOURCES: test-resources
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install JBang (ubuntu, macOS)
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          echo "$HOME/.jbang/bin" >> $GITHUB_PATH
      
      - name: Setup JBang (trusted sources)
        run: jbang trust add https://github.com/apache/

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup NodeJS 20
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Setup dependencies
        run: |
          npm install -g typescript @vscode/vsce
          vsce --version

      - name: npm-ci
        run: npm ci

      - name: npm-compile
        run: npm run compile

      - name: Allow unprivileged user namespace (ubuntu)
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: UI test
        run: xvfb-run --auto-servernum npm run ui-test

      - name: Store UI test log
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: uitest-logs
          path: test-resources/settings/logs/*

      - name: Store UI Test screenshots
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: uitest-screenshots
          path: test-resources/screenshots/*.png
